#########################################################################################
# Swagger ui & api docs
#########################################################################################
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui

# OpenAPI groups configuration: each group maps to controllers and is displayed separately in Swagger UI
openapi-config.groups[0].name=v1
openapi-config.groups[0].display-name=API v1
openapi-config.groups[0].packages-to-scan=eu.europa.ec.simpl.contract.consumption.controller.v1
openapi-config.groups[1].name=old
openapi-config.groups[1].display-name=API old (deprecated)
openapi-config.groups[1].packages-to-scan=eu.europa.ec.simpl.contract.consumption.controller.old

# comma separated list of servers url to be used by swagger
openapi-config.servers=https://contract-consumption.dev.simpl-europe.eu

# Security enabled (default=false)
openapi-config.security.enabled=true

# Set the title for Swagger UI
openapi-config.title=Contract Consumption API
openapi-config.description=This API enables the discovery, negotiation, and consumption of data contracts\n\
	between data providers and consumers in a secure and standardized way. It supports transfer initiation,\n\
	contract negotiation, and resource address management.\n\
	\n\
    ## Business Context\n\
    \n\
	The API facilitates data exchange in a federated data space. Consumers can search for data offers, negotiate contracts,\n\
	and initiate data transfers from providers. The API ensures secure and traceable interactions between participants.\n\
	\n\
    \n\
    ### Key Actors\n\
    \n\
    - **Provider**: Offers data assets.\n\
    - **Consumer**: Requests and consumes data.\n\
    \n\
    ### Typical Flow\n\
    \n\
    1. Search for data offers.\n\
    \n\
    2. Negotiate a contract.\n\
    \n\
    3. Initiate a transfer.\n\
    \n\
    4. Monitor transfer status.
